working_directory = 'D:\'

[shell]
program = 'C:\Users\Sanchit\scoop\apps\nu\current\nu.exe'

[window]
dimensions = { columns = 100, lines = 28 }
position = { x = 1900, y = 100 }
decorations = "None"
opacity = 0.8

[font]
normal = {family='Iosevka Term', style = 'Regular'}
size = 13

# Colors (Hyper)

# Default colors
[colors.primary]
background = '#000000'
foreground = '#ffffff'

[colors.cursor]
text = '#F81CE5'
cursor = '#ffffff'

# Normal colors
[colors.normal]
black   = '#000000'
red     = '#fe0100'
green   = '#33ff00'
yellow  = '#feff00'
blue    = '#0066ff'
magenta = '#cc00ff'
cyan    = '#00ffff'
white   = '#d0d0d0'

# Bright colors
[colors.bright]
black   = '#808080'
red     = '#fe0100'
green   = '#33ff00'
yellow  = '#feff00'
blue    = '#0066ff'
magenta = '#cc00ff'
cyan    = '#00ffff'
white   = '#FFFFFF'

[selection]
save_to_clipboard = true

[cursor]
style = {shape='Beam', blinking='Always'}

[terminal]
osc52 = 'CopyPaste'

[mouse]
hide_when_typing = true
bindings = [
{ mouse = "Right", action = "Paste" },
{ mouse = "Left" , action = "Copy"  },
]


